[package]
name = "entroppy-rust"
version = "0.8.0"
edition = "2021"

[lib]
name = "rust_ext"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["abi3-py38", "extension-module"] }
suffix = "1.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
